project:
  type: website
  output-dir: docs

website:
  title: "POLYMORPHIC GAMES"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: Games/index.qmd
      - text: "EDUCATION"
        file: Education/index.qmd
      - text: "PEOPLE"
        file: People/index.qmd
      - text: "BLOG"
        file: DevBlog/index.qmd

  sidebar:
    style: "docked"
    search: true
    contents: auto
          
        


format:
  html:
    theme: darkly
#    light: spacelab
#    dark: darkly
    css: styles.css
    toc: true




