project:
  type: website
  output-dir: docs

website:
  title: "Polymorphic Games"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - file: Games/index.qmd
      - text: "EDUCATION"
        file: Education/index.qmd
      - text: "PEOPLE"
        file: People/index.qmd
      - text: "BLOG"
        file: DevBlog/DevBlog.qmd

  sidebar:
    style: "docked"
    search: true
    contents: auto
          
        


format:
  html:
    theme: 
      light: spacelab
      dark: darkly
    css: styles.css
    toc: true




